#!/usr/bin/env python
import socket
from thread import *
import os
import RPi.GPIO as GPIO
import signal
import subprocess
import sys
import time
import string
import datetime
from time import strftime
from radio_class import Radio
from lcd_class import Lcd
import shutil
import urllib
from lcd_class import Lcd
from xml.dom import minidom
import getpass, poplib
import datetime
import time
from rss_class import Rss
rss = Rss()#rss-ul, of course
rss_txt=""
rss_1=rss.getFeed()
rss_1=rss.getFeed()
rss_next=rss.getFeed()
print rss_1
print rss_next
while rss_next!= rss_1:
	rss_txt=rss_txt+"\n"+rss_next
	rss_next=rss.getFeed()
print rss_txt
